name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      fail-fast: true

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry (v1.4.2)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "1.4.2"

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      - name: Run Forge tests
        env:
          MAINNET_API_KEY: ${{ secrets.MAINNET_API_KEY }}
        run: |
          forge verify-bytecode 0xF538909eDF14d2c23002C2b3882Ad60f79d61893 ObexEthereum_20251113.sol:ObexEthereum_20251113 --rpc-url https://eth.llamarpc.com
        id: verify
